spring:
  datasource:
    url: "jdbc:postgresql://localhost:5434/iprody"
    username: postgres
    password: postgres
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:4000/realms/iprody

