spring:
  application:
    name: clients
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: orders  
      maximum-pool-size: 5
      connection-timeout: 5000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
    default-schema: iprody-clients
    liquibase-schema: iprody-clients
    drop-first: false

server:
  port: 8081
