spring:
  application:
    name: clients
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:   
      maximum-pool-size: 5
      connection-timeout: 5000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml   
    drop-first: false

server:
  port: 8443
  ssl:
    key-store: classpath:security/keystore.p12
    key-store-password: changeit
    key-store-type: PKCS12
    key-alias: sbssl

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
      status:
        http-mapping:
          down: 503
  
  
